package org.the4thlaw.commons.services.logging;

import java.nio.file.Path;
import java.util.Locale;

import org.the4thlaw.commons.services.io.DirectoryServiceFactory;
import org.the4thlaw.commons.services.io.IDirectoryService;

import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.LoggerContext;
import ch.qos.logback.classic.encoder.PatternLayoutEncoder;
import ch.qos.logback.classic.spi.Configurator;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.classic.tyler.TylerConfiguratorBase;
import ch.qos.logback.core.ConsoleAppender;
import ch.qos.logback.core.rolling.RollingFileAppender;
import ch.qos.logback.core.rolling.TimeBasedRollingPolicy;

/**
 * Standardized logback configuration that is aware of the chosen directory service.
 * 
 * <p>
 * This file was initially generated by logback-tyler version 1.0.4
 * </p>
 *
 *
 * <p>
 * You may experiment with logback.xml to Java translation, i.e. TylerConfigurator generation, at the following URL:
 * </p>
 *
 * <p>
 * https://logback.qos.ch/translator/services/xml2Java.html
 * </p>
 *
 * <p>
 * This class requires logback-classic version 1.5.20 or later at runtime.
 * </p>
 *
 * <p>
 * Custom configurators are looked up via Java's service-provide facility. If a custom provider is found, it takes
 * precedence over logback's own configurators, e.g. DefaultJoranConfigurator.
 * </p>
 *
 * <p>
 * To install your custom configurator to your project, add a provider-configuration file to the following path:
 * </p>
 *
 * <pre>
 * {@code
 * META - INF / services / ch.qos.logback.classic.spi.Configurator
 * }
 * </pre>
 *
 * <p>
 * This provider-configuration file should contain a line with the fully qualified class name of your tyler
 * configurator.
 * </p>
 *
 * <p>
 * See also item 1 of 'Configuration at initialization' section at
 * </p>
 *
 * <p>
 * https://logback.qos.ch/manual/configuration.html#auto_configuration
 * </p>
 *
 * <p>
 * Configurations using TylerConfigurator can still dynamically configure logger levels with the help of properties
 * files. Moreover, configuration files in properties format can be watched for changes. See the documentation on
 * PropertiesConfigurator for more details.
 * </p>
 *
 * <p>
 * https://logback.qos.ch/manual/configuration.html#propertiesConfigurator
 * </p>
 * 
 * @since 1.5
 */
public abstract class BaseDirectoryServiceLogbackConfiguration extends TylerConfiguratorBase implements Configurator {
    protected final String appName;
    protected final String appNameLc;
    protected final String[] firstPartyPackages;
    protected final Path logDirectory;

    protected RollingFileAppender<ILoggingEvent> appender3rdParty;
    protected RollingFileAppender<ILoggingEvent> appenderApp;
    protected ConsoleAppender<ILoggingEvent> appenderConsole;

    protected BaseDirectoryServiceLogbackConfiguration(String appName, String... firstPartyPackages) {
        this.appName = appName;
        this.appNameLc = appName.toLowerCase(Locale.ROOT);
        this.firstPartyPackages = firstPartyPackages;
        IDirectoryService directoryService = new DirectoryServiceFactory()
                .withAppName(appName)
                .autoDetectImplementation()
                .autoDetectLegacy()
                .build();
        this.logDirectory = directoryService.getLogsDirectory();
    }

    /**
     * <p>
     * This method performs configuration per {@link Configurator} interface.
     * </p>
     *
     * <p>
     * If <code>TylerConfigurator</code> is installed as a configurator service, this method will be called by
     * logback-classic during initialization.
     * </p>
     */
    @Override
    public Configurator.ExecutionStatus configure(LoggerContext loggerContext) {
        setContext(loggerContext);
        this.appenderConsole = setupAppenderConsole();
        this.appenderApp = setupAppenderApp();
        this.appender3rdParty = setupAppender3rdParty();

        for (String first : firstPartyPackages) {
            Logger firstLogger = setupLogger(first, "INFO", Boolean.FALSE);
            firstLogger.addAppender(appenderConsole);
            firstLogger.addAppender(appenderApp);
        }

        Logger loggerROOT = setupLogger("ROOT", "WARN", null);
        loggerROOT.addAppender(appenderConsole);
        loggerROOT.addAppender(appender3rdParty);

        return ExecutionStatus.DO_NOT_INVOKE_NEXT_IF_ANY;
    }

    ConsoleAppender<ILoggingEvent> setupAppenderConsole() {
        ConsoleAppender<ILoggingEvent> appender = new ConsoleAppender<ILoggingEvent>();
        appender.setContext(context);
        appender.setName("console");

        // Configure component of type PatternLayoutEncoder
        PatternLayoutEncoder patternLayoutEncoder = new PatternLayoutEncoder();
        patternLayoutEncoder.setContext(context);
        patternLayoutEncoder
                .setPattern(
                        "%gray(%d{dd.MM.yyyy HH:mm:ss}) [%highlight(%-5level)] %cyan(%logger{36}:%L) %gray(-) %msg%n");
        patternLayoutEncoder.setParent(appender);
        patternLayoutEncoder.start();
        // Inject component of type PatternLayoutEncoder into parent
        appender.setEncoder(patternLayoutEncoder);

        appender.start();
        return appender;
    }

    private RollingFileAppender<ILoggingEvent> setupAppenderApp() {
        RollingFileAppender<ILoggingEvent> appender = new RollingFileAppender<ILoggingEvent>();
        appender.setContext(context);
        appender.setName(appName);
        appender.setFile(logDirectory.resolve(appNameLc + ".log").toAbsolutePath().toString());

        // Configure component of type TimeBasedRollingPolicy
        TimeBasedRollingPolicy<?> timeBasedRollingPolicy = new TimeBasedRollingPolicy<ILoggingEvent>();
        timeBasedRollingPolicy.setContext(context);
        timeBasedRollingPolicy.setFileNamePattern(
                logDirectory.resolve("archives").resolve(appNameLc + ".%d.log.zip").toAbsolutePath().toString());
        timeBasedRollingPolicy.setMaxHistory(30);
        timeBasedRollingPolicy.setParent(appender);
        timeBasedRollingPolicy.start();
        // Inject component of type TimeBasedRollingPolicy into parent
        appender.setRollingPolicy(timeBasedRollingPolicy);
        appender.setAppend(true);

        // Configure component of type PatternLayoutEncoder
        PatternLayoutEncoder patternLayoutEncoder = new PatternLayoutEncoder();
        patternLayoutEncoder.setContext(context);
        patternLayoutEncoder.setPattern("%d{dd.MM.yyyy HH:mm:ss} [%-5level] %logger{36}:%L - %msg%n");
        patternLayoutEncoder.setParent(appender);
        patternLayoutEncoder.start();
        // Inject component of type PatternLayoutEncoder into parent
        appender.setEncoder(patternLayoutEncoder);

        appender.start();
        return appender;
    }

    private RollingFileAppender<ILoggingEvent> setupAppender3rdParty() {
        RollingFileAppender<ILoggingEvent> appender = new RollingFileAppender<ILoggingEvent>();
        appender.setContext(context);
        appender.setName("3rdParty");
        appender.setFile(logDirectory.resolve("3rd-party.log").toAbsolutePath().toString());

        // Configure component of type TimeBasedRollingPolicy
        TimeBasedRollingPolicy<?> timeBasedRollingPolicy = new TimeBasedRollingPolicy<ILoggingEvent>();
        timeBasedRollingPolicy.setContext(context);
        timeBasedRollingPolicy.setFileNamePattern(
                logDirectory.resolve("archives").resolve("3rd-party.%d.log.zip").toAbsolutePath().toString());
        timeBasedRollingPolicy.setMaxHistory(30);
        timeBasedRollingPolicy.setParent(appender);
        timeBasedRollingPolicy.start();
        // Inject component of type TimeBasedRollingPolicy into parent
        appender.setRollingPolicy(timeBasedRollingPolicy);
        appender.setAppend(true);

        // Configure component of type PatternLayoutEncoder
        PatternLayoutEncoder patternLayoutEncoder = new PatternLayoutEncoder();
        patternLayoutEncoder.setContext(context);
        patternLayoutEncoder.setPattern("%d{dd.MM.yyyy HH:mm:ss} [%-5level] %logger{36}:%L - %msg%n");
        patternLayoutEncoder.setParent(appender);
        patternLayoutEncoder.start();
        // Inject component of type PatternLayoutEncoder into parent
        appender.setEncoder(patternLayoutEncoder);

        appender.start();
        return appender;
    }
}
