<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.the4thlaw</groupId>
		<artifactId>java-commons</artifactId>
		<version>1.5.0-SNAPSHOT</version>
	</parent>

	<artifactId>common-dao</artifactId>
	<packaging>jar</packaging>

	<name>The4thLaw Utils - Common Data Access Objects</name>
	<description>Common utilities for Java projects at https://github.com/The4thLaw - Common DAO</description>
	<inceptionYear>2024</inceptionYear>

	<properties>
		<project.rootdir>${project.basedir}/..</project.rootdir>
	</properties>

	<dependencies>
		<dependency>
			<groupId>jakarta.persistence</groupId>
			<artifactId>jakarta.persistence-api</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-commons</artifactId>
		</dependency>
	</dependencies>

</project>